# Generated by Django 3.1.2 on 2020-11-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201105_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='deporte',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
